on: [push]
name: build
jobs:
  stack:
    name: stack/ghc
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.0.2' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
      - name: Test
        run: |
          stack test --system-ghc
